### ISSUE TITLE
Make dump script not fail on unsupported tokens

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/contracts#28]
I had a token in my token list that is unsupported so creating an order failed. This caused the whole script to exit. I would be better if we logged a warning while continuing with the other tokens.

```
An unexpected error occurred:13...

Error: Calling "https://barn.api.cow.fi/mainnet/api/v1/quote {"method":"post","headers":{"Content-Type":"application/json"},"body":"{\"sellToken\":\"0x1C4853Ec0d55e420002c5eFaBc7Ed8e0bA7A4121\",\"buyToken\":\"0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2\",\"validTo\":1664288868,\"appData\":\"0x2947be33ebfa25686ec204857135dd1c676f35d6c252eb066fffaf9b493a01b4\",\"partiallyFillable\":false,\"from\":\"0x84E5c8518c248DE590D5302fD7C32d2Ae6B0123c\",\"kind\":\"sell\",\"sellAmountBeforeFee\":\"89617252764471\"}"} failed with 400: {"errorType":"UnsupportedToken","description":"Token address 0x1c4853ec0d55e420002c5efabc7ed8e0ba7a4121"}
    at call (/home/e/contracts/src/ts/api.ts:142:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getQuote (/home/e/contracts/src/tasks/dump.ts:349:25)
    at async Array.<anonymous> (/home/e/contracts/src/tasks/dump.ts:285:23)
    at async Promise.all (index 0)
    at async promiseAllWithRateLimit (/home/e/contracts/src/tasks/ts/rate_limits.ts:76:11)
    at async getDumpInstructions (/home/e/contracts/src/tasks/dump.ts:262:5)
    at async dump (/home/e/contracts/src/tasks/dump.ts:696:5)
    at async SimpleTaskDefinition.action (/home/e/contracts/src/tasks/dump.ts:897:9)
    at async Environment._runTaskDefinition (/home/e/contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14) {
  apiError: {
    errorType: 'UnsupportedToken',
    description: 'Token address 0x1c4853ec0d55e420002c5efabc7ed8e0ba7a4121'
  }
}
```

**Comment by mfw78** [comment]
No longer an issue with [`cow-fee`](https://github.com/cowdao-grants/cow-fee) which if the quote results with an unsupported token, it is filtered at the script level.
