### ISSUE TITLE
Build fails with latest @tenderly/hardhat-tenderly

### ISSUE THREAD

**Issue by nikola-matic** [cowprotocol/contracts#32]
Deleting `yarn.lock`, and the installing dependencies via `yarn`, and finally attempting `yarn build:sol` fails with the following error:
```
yarn run v1.22.18
$ yarn build:sol && yarn build:ts
$ hardhat compile --force
An unexpected error occurred:

Error: Cannot find module 'tenderly'
Require stack:
- /tmp/ext-test-Gnosis-Protocol-V2-mzyKps/ext/node_modules/@tenderly/hardhat-tenderly/dist/tasks/push.js
- /tmp/ext-test-Gnosis-Protocol-V2-mzyKps/ext/node_modules/@tenderly/hardhat-tenderly/dist/tasks/index.js
- /tmp/ext-test-Gnosis-Protocol-V2-mzyKps/ext/node_modules/@tenderly/hardhat-tenderly/dist/index.js
- /tmp/ext-test-Gnosis-Protocol-V2-mzyKps/ext/hardhat.config.ts
- /tmp/ext-test-Gnosis-Protocol-V2-mzyKps/ext/node_modules/hardhat/internal/core/config/config-loading.js
- /tmp/ext-test-Gnosis-Protocol-V2-mzyKps/ext/node_modules/hardhat/internal/cli/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/tmp/ext-test-Gnosis-Protocol-V2-mzyKps/ext/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/tmp/ext-test-Gnosis-Protocol-V2-mzyKps/ext/node_modules/@tenderly/hardhat-tenderly/src/tasks/push.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .js] (/tmp/ext-test-Gnosis-Protocol-V2-mzyKps/ext/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1037:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/ext-test-Gnosis-Protocol-V2-mzyKps/ext/node_modules/@tenderly/hardhat-tenderly/dist/tasks/push.js',
    '/tmp/ext-test-Gnosis-Protocol-V2-mzyKps/ext/node_modules/@tenderly/hardhat-tenderly/dist/tasks/index.js',
    '/tmp/ext-test-Gnosis-Protocol-V2-mzyKps/ext/node_modules/@tenderly/hardhat-tenderly/dist/index.js',
    '/tmp/ext-test-Gnosis-Protocol-V2-mzyKps/ext/hardhat.config.ts',
    '/tmp/ext-test-Gnosis-Protocol-V2-mzyKps/ext/node_modules/hardhat/internal/core/config/config-loading.js',
    '/tmp/ext-test-Gnosis-Protocol-V2-mzyKps/ext/node_modules/hardhat/internal/cli/cli.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
[@tenderly/hardhat-tenderly](https://www.npmjs.com/package/@tenderly/hardhat-tenderly) had a release today, which coincides with this failure; there is a warning about an unsatisfied dependency, namely:
```
warning " > @tenderly/hardhat-tenderly@1.3.0" has unmet peer dependency "tenderly@^0.0.2".
```
Oddly enough, downgrading to version `1.2.0` didn't work either (not sure why we didn't see that before), but that one also complains about unmet `tenderly@^0.0.1`, so that might be a clue.

Finally, downgrading to `@tenderly/hardhat-tenderly@1.1.6` allows the build to run normally.

**Comment by mfw78** [comment]
This issue appears to have been fixed in #49.
