### ISSUE TITLE
Self-sell task only works on mainnet

### ISSUE THREAD

**Issue by fedgiac** [cowprotocol/contracts#74]
The changes from #57 broke support for running the script on networks that aren't mainnet.
At this point in time, this feature is mostly useful when testing the script.

The error is unclear to the user, namely something like `There is no valid ERC20 token at address 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2`, where the address is a mainnet token.

<details><summary>Output</summary>

```
Using account 0xA03be496e67Ec29bC62F01a428683D7F9c204930
Script failed execution but no irreversible operations were performed
Error: There is no valid ERC20 token at address 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
    at Array.<anonymous> (/home/fedgiac/code/cow/contracts/src/tasks/selfSell.ts:301:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async promiseAllWithRateLimit (/home/fedgiac/code/cow/contracts/src/tasks/ts/rate_limits.ts:76:11)
    at async getOrders (/home/fedgiac/code/cow/contracts/src/tasks/selfSell.ts:421:5)
    at async prepareOrders (/home/fedgiac/code/cow/contracts/src/tasks/selfSell.ts:610:16)
    at async selfSell (/home/fedgiac/code/cow/contracts/src/tasks/selfSell.ts:787:36)
    at async SimpleTaskDefinition.action (/home/fedgiac/code/cow/contracts/src/tasks/selfSell.ts:981:9)
    at async Environment._runTaskDefinition (/home/fedgiac/code/cow/contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:14)
    at async Environment.run (/home/fedgiac/code/cow/contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:163:14)
An unexpected error occurred:

Error: There is no valid ERC20 token at address 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
    at Array.<anonymous> (/home/fedgiac/code/cow/contracts/src/tasks/selfSell.ts:301:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async promiseAllWithRateLimit (/home/fedgiac/code/cow/contracts/src/tasks/ts/rate_limits.ts:76:11)
    at async getOrders (/home/fedgiac/code/cow/contracts/src/tasks/selfSell.ts:421:5)
    at async prepareOrders (/home/fedgiac/code/cow/contracts/src/tasks/selfSell.ts:610:16)
    at async selfSell (/home/fedgiac/code/cow/contracts/src/tasks/selfSell.ts:787:36)
    at async SimpleTaskDefinition.action (/home/fedgiac/code/cow/contracts/src/tasks/selfSell.ts:981:9)
    at async Environment._runTaskDefinition (/home/fedgiac/code/cow/contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:14)
    at async Environment.run (/home/fedgiac/code/cow/contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:163:14)
```
</details>

**Comment by fleupold** [comment]
The new fee withdrawl mechanism uses events to get the tokens it should liquidate.
